//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contaminants_Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualConsumption
    {
        public int pkIndividualConsumptionId { get; set; }
        public Nullable<int> IndividualNumber { get; set; }
        public int fkGovernorateId { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<double> DC { get; set; }
        public Nullable<double> DM { get; set; }
        public Nullable<double> DY1 { get; set; }
        public Nullable<double> DY2 { get; set; }
        public Nullable<double> FD4 { get; set; }
        public Nullable<double> FO1 { get; set; }
        public Nullable<double> FO13 { get; set; }
        public Nullable<double> FO14 { get; set; }
        public Nullable<double> FO18 { get; set; }
        public Nullable<double> FO4 { get; set; }
        public Nullable<double> FO5 { get; set; }
        public Nullable<double> FO9 { get; set; }
        public Nullable<double> GR1 { get; set; }
        public Nullable<double> MM001 { get; set; }
        public Nullable<double> MP { get; set; }
        public Nullable<double> VP001 { get; set; }
        public Nullable<double> VP3 { get; set; }
        public Nullable<double> VR001 { get; set; }
        public Nullable<double> VR1 { get; set; }
        public Nullable<double> VR24 { get; set; }
        public Nullable<double> VR29 { get; set; }
    
        public virtual Governorate Governorate { get; set; }
    }
}
