//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contaminants_Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mycotoxin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mycotoxin()
        {
            this.LabSamples = new HashSet<LabSample>();
            this.MycotoxinMLs = new HashSet<MycotoxinML>();
        }
    
        public int pkMycotoxinId { get; set; }
        public string MycotoxinName { get; set; }
        public string PTWI { get; set; }
        public string PTWI_unit { get; set; }
        public string PTWI_ref { get; set; }
        public Nullable<double> cancer_potency { get; set; }
        public string cp_unit { get; set; }
        public string cp_ref { get; set; }
        public Nullable<double> BMDL10 { get; set; }
        public string BMDL10_uni { get; set; }
        public string BMDL10_ref { get; set; }
        public Nullable<double> PMTDI { get; set; }
        public string PMTDI_unit { get; set; }
        public string PMTDI_ref { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabSample> LabSamples { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MycotoxinML> MycotoxinMLs { get; set; }
    }
}
