//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contaminants_Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PesticideResidue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PesticideResidue()
        {
            this.LabSamples = new HashSet<LabSample>();
            this.PestResMRLs = new HashSet<PestResMRL>();
        }
    
        public int pkPesticideResidueId { get; set; }
        public string PestResName { get; set; }
        public string PestResCode { get; set; }
        public string ADI { get; set; }
        public Nullable<int> fkADI_UnitId { get; set; }
        public string ARFD { get; set; }
        public Nullable<int> fkARFD_UnitId { get; set; }
        public string Reference { get; set; }
        public Nullable<bool> Banned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabSample> LabSamples { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual UOM UOM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PestResMRL> PestResMRLs { get; set; }
    }
}
