//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contaminants_Monitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VetResMRL
    {
        public int pkVetResMRLId { get; set; }
        public int fkVetResidueID { get; set; }
        public double MRL { get; set; }
        public int fkUOMId { get; set; }
        public int fkCommodityId { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual UOM UOM1 { get; set; }
        public virtual VeterinaryResidue VeterinaryResidue { get; set; }
    }
}
